# ─────────────────────────────────────────────────────────────
# Stage 1 — Install dependencies
# ─────────────────────────────────────────────────────────────
FROM node:20-slim AS deps
RUN apt-get update && apt-get install -y openssl libssl-dev && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ─────────────────────────────────────────────────────────────
# Stage 2 — Build the application
# ─────────────────────────────────────────────────────────────
FROM node:20-slim AS builder
RUN apt-get update && apt-get install -y openssl libssl-dev && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# next.config.ts sets output: "standalone" which produces
# a minimal self-contained server in .next/standalone
RUN npm run build

# ─────────────────────────────────────────────────────────────
# Stage 3 — Production runtime (smallest possible image)
# ─────────────────────────────────────────────────────────────
FROM node:20-slim AS runner
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app

ENV NODE_ENV=production
# Disable Next.js telemetry in CI/production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user with a home directory to avoid npm EACCES issues
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 --home /app nextjs

# Copy only what's needed to run the server
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
